# Generated by Django 2.1.2 on 2019-01-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190101_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='follow',
            name='isRequest',
            field=models.BooleanField(default=False),
        ),
    ]
