# Generated by Django 2.1.2 on 2019-01-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190107_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentContent',
            field=models.CharField(max_length=100),
        ),
    ]
